---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-color
  namespace: devops-kubernetes

spec:
  containers:
    - name: webapp-color
      image: kodekloud/webapp-color
      imagePullPolicy: Always
      envFrom:
        - configMapRef:
            name: webapp-config-map
      resources: {}
