apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: devops-kubernetes
  labels:
    app: myapp
    type: front-end

spec:
  containers:
    - name: myapp
      image: nginx
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          memory: 200Mi
          cpu: 500m

